export const CATEGORY_SEED = [
  {
    name: 'Food',
    icon: 'food-fork-drink',
    type: 'expense',
    subcategories: [
      { name: 'Grocery', icon: 'cart' },
      { name: 'Coffee', icon: 'coffee' },
      { name: 'Restaurant', icon: 'silverware-fork-knife' },
      { name: 'Drinks', icon: 'glass-cocktail' },
      { name: 'Delivery', icon: 'truck-delivery' },
      { name: 'Snacks', icon: 'food-apple' },
      { name: 'Bar', icon: 'beer' },
      { name: 'Fast food', icon: 'hamburger' },
    ],
  },
  {
    name: 'Transport',
    icon: 'car',
    type: 'expense',
    subcategories: [
      { name: 'Bus', icon: 'bus' },
      { name: 'Taxi', icon: 'taxi' },
      { name: 'Train', icon: 'train' },
      { name: 'Fuel', icon: 'gas-station' },
      { name: 'Maintenance', icon: 'wrench' },
      { name: 'Airplane', icon: 'airplane' },
      { name: 'Subway', icon: 'subway-variant' },
      { name: 'Tramway', icon: 'tram' },
    ],
  },
  {
    name: 'Leisure',
    icon: 'gamepad-variant',
    type: 'expense',
    subcategories: [
      { name: 'Sports', icon: 'soccer' },
      { name: 'Movies', icon: 'movie-open' },
      { name: 'Artwork', icon: 'palette' },
      { name: 'Music', icon: 'music' },
      { name: 'Equipment', icon: 'basketball' },
      { name: 'Hotel', icon: 'bed' },
      { name: 'Museums & Exhibitions', icon: 'bank' },
      { name: 'Books', icon: 'book-open-variant' },
      { name: 'Drawing', icon: 'brush' },
      { name: 'Games', icon: 'gamepad' },
      { name: 'Nightclub', icon: 'glass-cocktail' },
      { name: 'Video', icon: 'video' },
    ],
  },
  {
    name: 'Housing',
    icon: 'home',
    type: 'expense',
    subcategories: [
      { name: 'Rent', icon: 'home-city' },
      { name: 'Furniture', icon: 'sofa' },
      { name: 'Decoration', icon: 'brush' },
      { name: 'Electricity', icon: 'flash' },
      { name: 'Equipment', icon: 'tools' },
      { name: 'Security', icon: 'shield-home' },
      { name: 'Sink', icon: 'water-pump' },
      { name: 'Heating', icon: 'fire' },
      { name: 'Hotel', icon: 'bed' },
      { name: 'Housekeeper', icon: 'broom' },
      { name: 'Phone', icon: 'phone' },
      { name: 'TV', icon: 'television' },
      { name: 'Water', icon: 'water' },
      { name: 'Waste profits', icon: 'trash-can' },
      { name: 'Condominium', icon: 'home-group' },
    ],
  },
  {
    name: 'Safety',
    icon: 'shield-check',
    type: 'expense',
    subcategories: [
      { name: 'Life insurance', icon: 'shield-heart' },
      { name: 'Mutual premiums', icon: 'account-group' },
      { name: 'Newsletters', icon: 'email-newsletter' },
      { name: 'Overtime', icon: 'clock-outline' },
      { name: 'Succession', icon: 'account-multiple' },
      { name: 'Miscellaneous', icon: 'dots-horizontal' },
    ],
  },
  {
    name: 'Health',
    icon: 'hospital-box',
    type: 'expense',
    subcategories: [
      { name: 'Generic', icon: 'medical-bag' },
      { name: 'Doctor', icon: 'stethoscope' },
      { name: 'Dentist', icon: 'tooth' },
      { name: 'Hospital', icon: 'hospital' },
      { name: 'Medication', icon: 'pill' },
      { name: 'Insurance', icon: 'shield-plus' },
      { name: 'Physiotherapist', icon: 'run' },
      { name: 'Optician', icon: 'eyeglasses' },
      { name: 'Social charges', icon: 'account-cash' },
      { name: 'Sports coach', icon: 'whistle' },
      { name: 'Social security', icon: 'shield-account' },
    ],
  },
  {
    name: 'Retirement',
    icon: 'account-tie',
    type: 'expense',
    subcategories: [
      { name: 'Retirement Fund', icon: 'bank' },
      { name: 'Supplementary pension', icon: 'cash-plus' },
    ],
  },
  {
    name: 'Investment income',
    icon: 'chart-line',
    type: 'income',
    subcategories: [
      { name: 'Capital gain', icon: 'chart-bar' },
      { name: 'Dividend', icon: 'cash-multiple' },
      { name: 'Interest', icon: 'percent' },
    ],
  },
  {
    name: 'Pets',
    icon: 'paw',
    type: 'expense',
    subcategories: [
      { name: 'Food', icon: 'bone' },
      { name: 'Grooming', icon: 'scissors-cutting' },
      { name: 'Various supplies', icon: 'package-variant' },
      { name: 'Veterinary surgeon', icon: 'stethoscope' },
    ],
  },
  {
    name: 'Insurance',
    icon: 'shield',
    type: 'expense',
    subcategories: [
      { name: 'Car', icon: 'car' },
      { name: 'Civil liability', icon: 'scale-balance' },
      { name: 'Health', icon: 'medical-bag' },
      { name: 'House', icon: 'home' },
      { name: 'Life', icon: 'heart' },
    ],
  },
  {
    name: 'Car',
    icon: 'car',
    type: 'expense',
    subcategories: [
      { name: 'Fines', icon: 'alert-circle' },
      { name: 'Fuel', icon: 'gas-station' },
      { name: 'Maintenance', icon: 'wrench' },
      { name: 'Parking', icon: 'parking' },
      { name: 'Repairs', icon: 'tools' },
    ],
  },
  {
    name: 'Children',
    icon: 'baby-face',
    type: 'expense',
    subcategories: [
      { name: 'Nurse', icon: 'baby-bottle' },
      { name: 'Studies', icon: 'school' },
    ],
  },
  {
    name: 'Studies',
    icon: 'school',
    type: 'expense',
    subcategories: [
      { name: 'Books', icon: 'book-open-page-variant' },
      { name: 'Lessons', icon: 'teach' },
      { name: 'School fees', icon: 'cash' },
    ],
  },
  {
    name: 'Professional expenses',
    icon: 'briefcase',
    type: 'expense',
    subcategories: [
      { name: 'Non refundable', icon: 'cancel' },
      { name: 'Refundable', icon: 'check-circle' },
    ],
  },
  {
    name: 'Taxes',
    icon: 'percent-box',
    type: 'expense',
    subcategories: [
      { name: 'Income tax', icon: 'cash-minus' },
      { name: 'Land tax', icon: 'home-city' },
    ],
  },
  {
    name: 'Other income',
    icon: 'cash-plus',
    type: 'income',
    subcategories: [
      { name: 'Family allowance', icon: 'account-group' },
      { name: 'Gambling', icon: 'cards-playing-outline' },
      { name: 'Mutual insurance', icon: 'handshake' },
      { name: 'Social security', icon: 'shield-account' },
      { name: 'Tax credit', icon: 'cash-refund' },
      { name: 'Unemployment benefit', icon: 'account-cash' },
    ],
  },
  {
    name: 'Financial expenses',
    icon: 'bank',
    type: 'expense',
    subcategories: [
      { name: 'Bank charges', icon: 'credit-card' },
      { name: 'Loans', icon: 'file-document-outline' },
      { name: 'Loan repayments', icon: 'cash-multiple' },
      { name: 'Refinancing', icon: 'sync' },
    ],
  },
];
