const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

const inputDir = path.join(__dirname, '../assets/category-icons-optimized');
const outputDir = path.join(__dirname, '../assets/category-icons-optimized');

// Create output directory if it doesn't exist
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

// Convert category name to camelCase or snake_case logic to just strip spacing for keys if we wanted to
// But we can just use the exact basename of the file as keys.

const generateMap = true; // Whether to also generate categoryImages.ts

async function processImages() {
    try {
        const files = fs.readdirSync(inputDir);
        const imageFiles = files.filter(f => f.match(/\.(png|jpg|jpeg|webp)$/i));
        
        console.log(`Found ${imageFiles.length} images to process...`);
        
        let mapEntries = [];

        for (const file of imageFiles) {
            const inputPath = path.join(inputDir, file);
            // Always output webp to save space
            const ext = path.extname(file);
            const baseNameNoExt = path.basename(file, ext);
            
            // Output file path
            const outputFilename = `${baseNameNoExt}.webp`;
            const outputPath = path.join(outputDir, outputFilename);

            // Compress the image
            // We'll resize them to be highly optimized icons while maintaining aspect ratio (fit: 'inside')
            // Using max width/height of 256 for good quality but low file size
            // await sharp(inputPath)
            //     .resize(256, 256, {
            //         fit: 'inside', // Maintains aspect ratio, fitting within 256x256
            //         withoutEnlargement: true // Don't enlarge if already smaller
            //     })
            //     .webp({ quality: 80, effort: 6 }) // High compression effort
            //     .toFile(outputPath);
            
            console.log(`Mapped: ${file} -> ${outputFilename}`);
            
            // Prepare map entry (key is the label/filename without extension)
            // Using the exact filename (minus extension) as key allows easy lookup, but we lower case it for case-insensitivity
            const caseInsensitiveKey = baseNameNoExt.toLowerCase();
            mapEntries.push(`  '${caseInsensitiveKey.replace(/'/g, "\\'")}': require('../../assets/category-icons-optimized/${outputFilename.replace(/'/g, "\\'")}')`);
        }

        console.log('\nKeys mapped successfully!');

        if (generateMap) {
            const mapContent = `// Automatically generated by scripts/compressIcons.js
// Do not edit manually

export const CategoryImages: Record<string, any> = {
${mapEntries.join(',\n')}
};
`;
            const mapOutputPath = path.join(__dirname, '../src/utils/categoryImages.ts');
            fs.writeFileSync(mapOutputPath, mapContent, 'utf8');
            console.log(`Generated category mapping file at ${mapOutputPath}`);
        }

    } catch (err) {
        console.error('Error processing images:', err);
    }
}

processImages();
